### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by whoot** [digininja/RSMangler#10]
Trying to use rsmangler results in an undefined method error:
```
./rsmangler.rb --file wordlist.txt 
test
me

testme
metest
Traceback (most recent call last):
	2: from rsmangler.rb:375:in `<main>'
	1: from rsmangler.rb:375:in `each'
rsmangler.rb:376:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
```

Wordlist contains:
```
test
me
123
```

**Comment by Raslin777** [comment]
I have the same error. 

The error seems to come at the end mangling.

**Comment by sh1va73** [comment]
I am having the same error.

**Comment by ethicalhack3r** [comment]
Unable to reproduce on my environment:

- macOS 10.14.5
- ruby 2.6.3

**Comment by ethicalhack3r** [comment]
Was able to reproduce when adding an empty new line to the wordlist file

**Comment by sh1va73** [comment]
> Was able to reproduce when adding an empty new line to the wordlist file

Yes I tried again and now its working. I think I had an empty line when I got the error. Thanks for getting back!

**Comment by whoot** [comment]
Works great! Even with an empty line between entries.
Closed.
