### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by frankenstein91** [digininja/RSMangler#2]
can you please use the disk to buffer?

/rsmangler.rb:325: [BUG] object allocation during garbage collection phase
ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]

-- Control frame information -----------------------------------------------
c:0007 p:---- s:0058 e:000057 CFUNC  :join
c:0006 p:0011 s:0055 e:000053 BLOCK  ./rsmangler.rb:325 [FINISH]
c:0005 p:---- s:0051 e:000050 CFUNC  :permutation
c:0004 p:0014 s:0047 e:000046 BLOCK  ./rsmangler.rb:325 [FINISH]
c:0003 p:---- s:0044 e:000043 CFUNC  :each
c:0002 p:0885 s:0041 E:000bf0 EVAL   ./rsmangler.rb:324 [FINISH]
c:0001 p:0000 s:0002 E:0020bc TOP    [FINISH]

./rsmangler.rb:324:in `<main>'
./rsmangler.rb:324:in`each'
./rsmangler.rb:325:in `block in <main>'
./rsmangler.rb:325:in`permutation'
./rsmangler.rb:325:in `block (2 levels) in <main>'
./rsmangler.rb:325:in`join'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------
- Loaded script: ./rsmangler.rb
- Loaded features:
  
  0 enumerator.so
  1 /usr/lib/i386-linux-gnu/ruby/2.1.0/enc/encdb.so
  2 /usr/lib/i386-linux-gnu/ruby/2.1.0/enc/trans/transdb.so
  3 /usr/lib/i386-linux-gnu/ruby/2.1.0/rbconfig.rb
  4 /usr/lib/ruby/2.1.0/rubygems/compatibility.rb
  5 /usr/lib/ruby/2.1.0/rubygems/defaults.rb
  6 /usr/lib/ruby/2.1.0/rubygems/deprecate.rb
  7 /usr/lib/ruby/2.1.0/rubygems/errors.rb
  8 /usr/lib/ruby/2.1.0/rubygems/version.rb
  9 /usr/lib/ruby/2.1.0/rubygems/requirement.rb
  10 /usr/lib/ruby/2.1.0/rubygems/platform.rb
  11 /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb
  12 /usr/lib/ruby/2.1.0/rubygems/stub_specification.rb
  13 /usr/lib/ruby/2.1.0/rubygems/util/stringio.rb
  14 /usr/lib/ruby/2.1.0/rubygems/specification.rb
  15 /usr/lib/ruby/2.1.0/rubygems/exceptions.rb
  16 /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb
  17 /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb
  18 thread.rb
  19 /usr/lib/i386-linux-gnu/ruby/2.1.0/thread.so
  20 /usr/lib/ruby/2.1.0/monitor.rb
  21 /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb
  22 /usr/lib/ruby/2.1.0/rubygems.rb
  23 /usr/lib/i386-linux-gnu/ruby/2.1.0/date_core.so
  24 /usr/lib/ruby/2.1.0/date/format.rb
  25 /usr/lib/ruby/2.1.0/date.rb
  26 /usr/lib/ruby/2.1.0/getoptlong.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abgebrochen (Speicherabzug geschrieben)

**Comment by stephanpieterse** [comment]
Please see [this pull request](https://github.com/RandomStorm/RSMangler/pull/3) as this might solve your issue, otherwise available at [this fork](https://github.com/stephanpieterse/RSMangler) for the time being

**Comment by digininja** [comment]
direct outputting is now being implemented so no more memory caching.
