### ISSUE TITLE
leet speak swapping doesn't happen for all character swaps

### ISSUE THREAD

**Issue by darburn** [digininja/RSMangler#4]
When rsmangler does the leet speak substition, if a character should be swapped with more than one other character (e.g. a => 4 and a => @), only the last character swap occurs.  That is, a will only ever be swapped with @, and there is no output where a is swapped with 4.

**Comment by digininja** [comment]
Implementing a new leet speak function that should do everything you need. Check the file branch to see if it works for you.

**Comment by digininja** [comment]
Just pushed a set of changes to master, if the problem is still there let me know.
